server:
  forward-headers-strategy: native
  # https://www.baeldung.com/spring-boot-custom-error-page
  # https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-error-handling-custom-error-pages
  error:
    whitelabel:
      enabled: false
    path: /error
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1KB
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anima
    username: ${MYSQL_USER:jung}
    password: ${MYSQL_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
      idle-timeout: 100000
      max-lifetime: 3000000
      read-only: false
      connection-init-sql: "SET SESSION sql_mode='TRADITIONAL,NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY'"
      auto-commit: false